name: Main

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

env:
  DOCKER_HUB_REPOSITORY: ivangabriele/functionary

jobs:
  build_and_release:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      # https://github.com/easimon/maximize-build-space#inputs
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          remove-android: "true"
          remove-codeql: "true"
          remove-docker-images: "true"
          remove-dotnet: "true"
          remove-haskell: "true"
          root-reserve-mb: 512
          swap-size-mb: 1024
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: docker build -t ${{ env.DOCKER_HUB_REPOSITORY }}:latest .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
      - name: Push to Docker Hub
        run: docker push ${{ env.DOCKER_HUB_REPOSITORY }}:latest
      - name: Update Docker Hub Readme
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
          repository: ${{ env.DOCKER_HUB_REPOSITORY }}
